MyWeb/Models/Image.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MyWeb.Models
{

    [Table("index-img")]
    public class Image
    {
        [Key]
        [Column("img_id")]
        public int img_id { get; set; }

        [Column("img_name")]
        public string img_name { get; set; }

        [Column("img_path")]
        public string img_path { get; set; }

        [Column("img_type")]
        public string img_type { get; set; }

        [Column("img_active")]
        public int img_active { get; set; }


        public Image()
        {
        }



    }
}

MyWeb/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MyWeb.Models
{

    [Table("user")]
    public class User
    {
        [Key]
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_Password { get; set; }
        public string user_email { get; set; }
        public string user_imgPath { get; set; }

        public User()
        {
            user_id = 0;
            user_name = "";
            user_Password = "";
            user_email = "";
            user_imgPath = "";
        }
    }
}

MyWeb/Controllers/BaseController.cs
using MyWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MyWeb.Controllers
{
    public class BaseController : Controller
    {

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);

            setTopBar();
        }

        private void setTopBar()
        {
            var navList = new List<Item>()
            {
                new Item{ Name = "首页" , RouterSrc = "Index" , Controller = "Home"},
                new Item{ Name = "资源" , RouterSrc = "Paper" , Controller = "Home"},
                new Item{ Name = "资讯", RouterSrc = "Computer" , Controller = "Home"},
                new Item{ Name = "询问", RouterSrc = "AskQuestion" , Controller = "Home"},
                new Item{ Name = "关于我们", RouterSrc = "About" , Controller = "Home"}

            };

            ViewBag.navList = navList;

            UserViewModel userViewModel = new UserViewModel();
            ViewBag.UserViewModel = userViewModel;

        }

    }

    public class TopBarViewModel
    {
        public List<Item> NavLinks { get; set; }
    }

    public class UserViewModel
    {
        public UserViewModel()
        {
            user = new User();
            IsLogin = false;
        }
        public User user { get; set; }
        public bool IsLogin { get; set; }


    }

    public class Item
    {
        public string Name { get; set; }
        public string RouterSrc { get; set; }

        public string Controller {  get; set; }


    }
}

MyWeb/Controllers/httpController/ForgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyWeb.Controllers.viewController
{
    public class ForgetController : BaseController
    {
        // GET: Forget
        public ActionResult ForgetIndex()
        {
            return View();
        }
        public ActionResult ForgetSuccess()
        {   
            return View();
        }
    }
}

MyWeb/Controllers/httpController/IndexHttpController.cs
using MyWeb.Service;
using System;
using System.Collections.Generic;
using MyWeb.Models;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyWeb.Controllers.httpController
{

    
    public class IndexHttpController:BaseController
    {

        private readonly ImgService _imgService;

        public IndexHttpController()
        {
            _imgService = new ImgService();
        }

        [HttpGet]
        public ActionResult IndexImg()
        {
            List<Image> imgs = _imgService.GetIndexImgs();
            return Json(imgs, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Hello()
        {
            Response.Write("Hello World!");
            return Content("Hello World!");
        }
    }
}

MyWeb/Controllers/httpController/LoginController.cs
using Mysqlx;
using MyWeb.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyWeb.Controllers.viewController
{
    public class LoginController:BaseController
    {
        private readonly UserService _userServices;
        public LoginController()
        {
            _userServices = new UserService();
        }

        public ActionResult LoginIndex()
        {

            return View();
        }


        [HttpPost]
        public ActionResult LoginGet(string user_email, string user_password)
        {
            _userServices.Login(user_email, user_password);
            return Json("ok");
        }
    }

    public class LoginSet
    {

    }
}

MyWeb/Controllers/httpController/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyWeb.Controllers.viewController
{
    public class RegisterController : BaseController
    {
        // GET: Register
        public ActionResult RegisterIndex()
        {
            return View();
        }
    }
}

MyWeb/Controllers/viewController/HomeController.cs
using MyWeb.Dao;
using MyWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyWeb.Controllers
{
    public class HomeController : BaseController
    {
        private ImgDao imgDao = new ImgDao();
        public ActionResult Index()
        {
            ViewBag.Title = "首页"; 
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult AskQuestion()
        {
            return View();
        }



    }
}

MyWeb/Controllers/viewController/TextShowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyWeb.Controllers.viewController
{
    public class TextShowController : Controller
    {
        // GET: TextShow
        public ActionResult Index()
        {
            return View();
        }
    }
}

MyWeb/Views/Forget/ForgetIndex.cshtml
@{
    ViewBag.Title = "ForgetIndex";
}

@section Styles {
    <link href="~/Content/Forget.css" rel="stylesheet" />
}


<div class="forgot-password-box">
    <h2>忘记密码</h2>
    <form action="#" id="forgot-password-form">
        <div class="user-box">
            <input type="email" name="email" required>
            <label>邮箱</label>
        </div>
        <div class="user-box" id="verification-code-box">
            <input type="text" name="verification-code" required style="width: 75%;">
            <label>验证码</label>
            <button type="button" id="send-verification-code" style="margin-left: 10px; width:25%">发送</button>
        </div>

        <button type="submit">确认</button>
        <div class="links">
            <a href="@Url.Action("LoginIndex","Login")">返回登录</a>
        </div>
    </form>
</div>

MyWeb/Views/Forget/ForgetSuccess.cshtml
@{
    ViewBag.Title = "ForgetSuccess";
}
@section Styles {
    <link href="~/Content/Forget.css" rel="stylesheet" />
}


<div class="forgot-password-box">
    <h2>忘记密码</h2>
    <form action="#" id="forgot-password-form">
        <div class="user-box" id="reset-password-box">
            <input type="password" name="new-password" required>
            <label>新密码</label>
        </div>
        <div class="user-box" id="confirm-password-box">
            <input type="password" name="confirm-password" required>
            <label>确认密码</label>
        </div>
        <button type="submit" id="reset-password-btn">重置密码</button>
        <div class="links">
            <a href="@Url.Action("LoginIndex","Login")">返回登录</a>
        </div>
    </form>
</div>

MyWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">

</main>

MyWeb/Views/Home/AskQuestion.cshtml
@{
    ViewBag.Title = "AskQuestion";
}

<div>
    111
</div>

MyWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">


</main>

MyWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "首页";
}
@section Styles {
    <link href="~/Content/Index.css" rel="stylesheet" />
}
<main>
    <div class="Index-container back_img">
        <div class="img-container">
            <button id="left" class="slider-button slider-left">←</button>
            <img src="" alt="首页" />
            <button id="right" class="slider-button slider-right">→</button>
        </div>
    </div>

    <div class="back-contain history-contain">
        <div class="base-box base-title">
            人物风云：
        </div>
    </div>

    <div class="base-box">
        <div class="">

        </div>
    </div>



    <div class="music-title-contain back-contain">
        <div class="music-text base-title">
            盗版音乐：
        </div>
    </div>

    <div class="music-contain">
        <div class="music-Box">
            @for (int i = 0; i < 9; i++)
            {
                <div class="music-itemBox">
                    j
                </div>
            }
        </div>
    </div>

    <div class="back-contain history-contain">
        <div class="base-box base-title">
            学习版游戏：
        </div>
    </div>
</main>
@section Scripts {
    <script src="~/Scripts/Index.js"></script>
}

MyWeb/Views/Login/LoginIndex.cshtml
@{
    ViewBag.Title = "LoginIndex";
}
@section Styles {
    <link href="~/Content/LoginBox.css" rel="stylesheet" />
}
@section Scripts {
    <script src="~/Scripts/LoginSend.js"></script>
}

<div class="login-box">
    <h2>登录</h2>
    <form>
        <div class="user-box">
            <input type="text" id="user_email" name="username" required>
            <label>邮箱</label>
        </div>
        <div class="user-box">
            <input type="password" id="user_password" name="password" required>
            <label>密码</label>
        </div> 
        <button id="LoginSend" onclick="loginSend(event)" return false;>
            登录
        </button>
        <div class="links"> 
            <a href="@Url.Action("ForgetIndex","Forget")">忘记密码？</a>
            <a href="@Url.Action("RegisterIndex","Register")">注册新账号</a>
        </div>
    </form>
</div>

MyWeb/Views/Register/RegisterIndex.cshtml
@{

    ViewBag.Title = "注册";
}
@section Styles {
    <link href="~/Content/Register.css" rel="stylesheet" />
}
@section Scripts {
    <script src="~/Scripts/Register.js"></script>
}

<div class="register-box">
    <h2>注册</h2>
    <form action="#" id="register-form">
        <div class="user-box">
            <input type="text" name="username" required>
            <label>用户名</label>
        </div>
        <div class="user-box">
            <input type="email" name="email" required>
            <label>邮箱</label>
        </div>
        <div class="user-box">
            <input type="password" name="password" required>
            <label>密码</label>
        </div>
        <div class="user-box">
            <input type="password" name="confirm-password" required>
            <label>确认密码</label>
        </div>
        <button type="submit">注册</button>
        <div class="links">
            <a href="@Url.Action("LoginIndex","Login")">返回登录</a>
        </div>
    </form>
</div>

MyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 学习版资源 - @ViewBag.Title</title>
    <link href="~/Content/TopCon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.7.0.min.js"></script>
    <script src="~/Scripts/jquery-3.7.0.js"></script>
</head>
<body>
    <script>
        var appState = {
            isLoggedIn:@Html.Raw(Json.Encode(ViewBag.userViewModel.IsLogin)),
            user:@Html.Raw(Json.Encode(ViewBag.userViewModel.user))

        }
    </script>
    <script src="~/Scripts/Layout.js"></script>
    <div class="setTop">
        <div class="container">
            <div class="topShow">

                <div class="toplogo">

                    <img src="~/img/MyLogo.png" alt="none" />
                </div>


                <nav class="TopBar">
                    <ul>

                        @foreach (var item in ViewBag.navList)
                        {
                            <div>
                            <li>
                                <a href="@Url.Action(item.RouterSrc, item.Controller)">@item.Name</a>
                            </li>
                </div>

            }
                        </ul>
                        </nav>

                        <div class="topuserpic">
                            <img src="~/img/cks.jpg" alt="">
                        </div>

                        <div>
                            <div class="toplogin">
                                <a href="@Url.Action("LoginIndex","Login")">登录</a>
                            </div>
                        </div>

                    </div>
                </div>
                </div>


                <div class="main">
                    @RenderSection("Scripts", required: false)

                    @RenderSection("Styles", required: false)
                    @RenderBody()

                </div>

                <footer>
                    <!-- 底部内容 -->
                </footer>




            </body>
</html>